version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: tereo_homepage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:password@postgres:5432/tereo_homepage?schema=public"
      NEXTAUTH_URL: "http://localhost:3000"
      NEXTAUTH_SECRET: "your-secret-key-here"
      ADMIN_EMAIL: "admin@tereo.com"
      ADMIN_PASSWORD: "admin123"
    depends_on:
      - postgres
    command: >
      sh -c "
        npx prisma db push &&
        npx prisma db seed &&
        npm start
      "

volumes:
  postgres_data:
